# Lab 1: Introduction to NumPy
Machine Learning 2024/2025 <br>
Author: Machine Learning Teaching Team TU Delft

**WHAT** This nonmandatory lab consists of several programming and insight exercises/questions. 

**WHY** The exercises are meant to prepare you for using Python and NumPy in this course. 

**HOW** Follow the exercises in the notebooks either on your own or with a fellow student. For questions and feedback please consult the TA's during the lab session. 

We advise you to follow this notebook and use it as a reference for later. __Make sure that you have followed the Python tutorial (intro1-python).__ These tutorials cover a whole lot of Python and NumPy and you don't have to know everything by heart right away. But it is important to be aware of the total picture as this helps while making later assignments. You will find that you will be better able to troubleshoot if you run into a problem. If, after walking through these tutorials, you still feel uncomfortable with Python, we recommend the following tutorials:
* [The Python Tutorial] 
* [Python Numpy Tutorial]


[Python Numpy Tutorial]: http://cs231n.github.io/python-numpy-tutorial/

[The Python Tutorial]: https://docs.python.org/3/tutorial/index.html

This tutorial consists of two steps: first, you will get familiarized with the basic operations on arrays in NumPy, after which you get to practice with a number of exercises. If you want more in-depth understanding of NumPy, we highly recommend [Stanfords NumPy tutorial]!

[Stanfords NumPy tutorial]: http://cs231n.github.io/python-numpy-tutorial/

## Step 1: Array programming with NumPy

In this step we will show you the basics of array manipulation in NumPy.

We strongly advise you to reference and read the manuals and tutorials on the web to make sure you learn how to use modern array manipulation to unleash its true power.

In machine learning we are dealing with massive amounts of data. This data is most often organised in tables (like for example in spreadsheets). When all data elements in a table are of the same datatype (like an integer or a floating point number) the table can be represented with a homogeneous array.

Languages that are optimally suited for programming with data (like NumPy) are therefore equipped with array data types as an integral part of the language. An array is a data type to store lists of values. We can also create arrays of arrays, resulting in multi-dimensional arrays. NumPy provides tools to work with these multi-dimensional arrays in the form of the [`ndarray` class](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html).

Let's first import the NumPy library:

In [1]:
import numpy as np

### Declaring a regular Python list

In [2]:
list1 = [1, 2, 3, 4]
type(list1)

list

### Making a numpy array using Python lists

In [3]:
array1 = np.array(list1)
array1

array([1, 2, 3, 4])

In [4]:
# The type of array1 is an ndarray: an n-dimensional array
type(array1)

numpy.ndarray

In [5]:
print(array1)

[1 2 3 4]


### We can also use more dimensions

In [6]:
# Declare an extra list.
list2 = [11, 22, 33, 44]
# Combine the lists into a 2-dimensional list.
lists = [list1, list2]
lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [7]:
# make a 2-dimensional NumPy array
array2 = np.array(lists)
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

### And print their shapes
We would obviously expect a (4,1) and a (4,2)... or don't we?

In [8]:
print("Arr1: ", array1.shape)
print("Arr2: ", array2.shape)

Arr1:  (4,)
Arr2:  (2, 4)


The best way to think about NumPy arrays is that they consist of two parts, a _data buffer_ which is just a block of raw elements, and a _view_ which describes how to interpret the data buffer.

Here the shape `(4,)` means the array is indexed by a single index which runs from 0 to 3. The comma in `(4,)` is there to show that it is a tuple of integers, which is the data type of the shape attribute. Without the comma, it would simply be an integer, not a tuple of integers.

In most situations the lack of a second dimension is not a problem. If it does turn into a problem (e.g. when you are trying to take a transpose of this vector) you can just call the `reshape` function on the array to generate a new view:

In [9]:
# Do note the double brackets, as the size is added as a tuple: (rows, columns)
array1 = array1.reshape((4,1))
array1.shape

(4, 1)

For the above examples, we happen to know what we stored in our array, but in some cases we are not aware (like when we imported lots of data). To find out, you can call `dtype`:


In [10]:
array2.dtype

dtype('int64')

### Initializing regularly used arrays
There are also basic ways to initialize certain arrays which are used regularly, such as:

In [11]:
# The empty array (makes an array but doesn't do any initialisation)
print("Ex1: ", np.empty(5))

# Array of 5 floating point zeros
print("Ex2: ", np.zeros(5))

# Array of 5 floating point ones
print("Ex3: ", np.ones(5))

# Array of 5 integer incrementing numbers
print("Ex4: ", np.arange(5))

# Start at 5, stop at 20, do it in steps of 2
print("Ex5: ", np.arange(5, 20, 2))

# Making the identity matrix (ones on the diagonal)
print("Ex6: ")
print(np.eye(5))

Ex1:  [2.92122498e-315 0.00000000e+000 2.92941039e-315 2.88592866e-315
 2.37151510e-322]
Ex2:  [0. 0. 0. 0. 0.]
Ex3:  [1. 1. 1. 1. 1.]
Ex4:  [0 1 2 3 4]
Ex5:  [ 5  7  9 11 13 15 17 19]
Ex6: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Mathematical operations


The power of NumPy lies in the mathematical operations you can apply on those arrays. These are applied element-wise, which means that the operation is performed on each individual element in the array. Linear Algebra operations, like matrix multiplication or dot product are performed with special NumPy functions, like `np.matmul` or `np.dot`.

In [12]:
array3 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])
array3

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [13]:
# Element-wise multiplication
array3 * array3

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [14]:
# Element-wise subtraction
array3 - 5

array([[-4, -3, -2, -1],
       [ 3,  4,  5,  6]])

In [15]:
# Division
1 / array3

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [16]:
# Raising to a power
array3 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

### You can also apply functions to all elements in an array at once

The nice thing about NumPy arrays is that it allows you to manipulate the data in arrays without writing explicit loops. For instance look at the addition of all elements in an array:

In [17]:
# Array of random numbers
a = np.random.rand(65536)

In [18]:
#calculate the sum of the elements in array
def loopsum(a):
    sum = 0
    for i in range(len(a)):
        sum += a[i]
    return sum

In [19]:
%timeit loopsum(a)
%timeit np.sum(a)

7.14 ms ± 63.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
17.9 μs ± 1.01 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


You can see that the numpy loop is about 350 times faster than the explicit loop version.
So be aware in this course to use built-in NumPy tools to manipulate and calculate with arrays.
Some built-in functions of NumPy can be found [here].



[here]: https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations



### Indexing Arrays

In [20]:
array4 = np.arange(0, 10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

There is a minor difference when it comes to indexing compared to Python lists: namely that a NumPy array allows an additional indexing method:

In [21]:
list3 = [[1, 2, 3], [4, 5, 6]]
array5 = np.array(list3)

# Watch the brackets closely.
print("List: ", list3[1][2])
# Array can use two different approaches
print("Array ", array5[1, 2])
print("Array ", array5[1][2])

List:  6
Array  6
Array  6


### Slicing arrays
Sometimes you do not want the full array, but just parts of it, we can use array slicing for this:

In [22]:
# Show original array
print(array5)
# We want the element from the second row and third column:
print(array5[1:2,2:3])

[[1 2 3]
 [4 5 6]]
[[6]]


In [23]:
# We can also use it to set the value of multiple entries:
array4 = np.arange(0, 10)
array4[2:5] = 13
print(array4)

[ 0  1 13 13 13  5  6  7  8  9]


One important thing to note is that a slice is just another _view_ of the underlying data buffer. If you change data in the slice, you are actually changing the data in the underlying data buffer and thus in the orginal array. This is advantageous for the memory efficiency of your program, but sometimes it can cause errors when overlooked.

In [24]:
array4 = np.arange(0, 10)
# Take a slice, consisting of the 3rd (index 2) to 6th (index 5) element.
slice_array4 = array4[2:6]
# We iterate over all values, setting them to 22
slice_array4[:] = 22
print(slice_array4)
print(array4)

[22 22 22 22]
[ 0  1 22 22 22 22  6  7  8  9]


To prevent this, we can also make a new copy. In this way we do not generate a view, but actually reserve new memory for the object we are making:

In [25]:
array4 = np.arange(0, 10)
array5 = array4.copy()
print(array4)
print(array5)
array5[:] = 22
print("So did we make a copy?")
print(array4)
print(array5)
print("Seems we did.")

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
So did we make a copy?
[0 1 2 3 4 5 6 7 8 9]
[22 22 22 22 22 22 22 22 22 22]
Seems we did.


#### 2D array slicing

In [26]:
array6 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print(array6)
# let's say you only want just the upper right square of 2x2 of the above matrix
# reminder: when indexing with array[start:stop]
# the element at start is *included*, while the elemnt at stop is *excluded*
array6[:2, 1:]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[ 4,  6],
       [10, 12]])

#### Fancy Indexing
Sometimes you don't want to retrieve every row, but perhaps skip a few entries. This is easily possible in Python. Let us assume we only want the 2nd, 3rd, 5th, and 7th row in the following example.

In [27]:
# Below we use a list comprehension (which you should have seen in Introduction to Programming as well)
# To generate an array with 10 rows, and each column goes from 0 to 10.
array7 = np.array([[j for i in range(10)] for j in range(10)])
print(array7)
# As we start at index 0, we actually want the following rows [1, 2, 4, 6].
# Also note the double brackets below.
print("With fancy indexing:")
print(array7[[1, 2, 4, 6]])

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]
With fancy indexing:
[[1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [4 4 4 4 4 4 4 4 4 4]
 [6 6 6 6 6 6 6 6 6 6]]


You can do the above even in any order you wish.

In [28]:
array7[[6, 2, 4, 1]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### Array Transposition

In [29]:
array8 = np.arange(40).reshape((8, 5))
array8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [30]:
# If you want to transpose a matrix you can do this in two ways:

print(np.transpose(array8))
# Or
print(array8.T)

[[ 0  5 10 15 20 25 30 35]
 [ 1  6 11 16 21 26 31 36]
 [ 2  7 12 17 22 27 32 37]
 [ 3  8 13 18 23 28 33 38]
 [ 4  9 14 19 24 29 34 39]]
[[ 0  5 10 15 20 25 30 35]
 [ 1  6 11 16 21 26 31 36]
 [ 2  7 12 17 22 27 32 37]
 [ 3  8 13 18 23 28 33 38]
 [ 4  9 14 19 24 29 34 39]]


### Array Processing

We can also apply functions on arrays to retrieve specific information from them, or to process the information that is contained. In this section, we will survey a number of these handy functions.

#### Numpy Where

When you want to find the location of elements in an array, you can use `np.where`. This function takes in a condition and returns the indices of the array where the condition is true.

In [31]:
# A simple np.where example:
A = np.array([1, 2, 3, 4])
indices = np.where(A < 3)
print(indices)
print(A[indices])

(array([0, 1]),)
[1 2]


#### Numpy Any & All

As shown before, we can apply a boolean operator on an array, which will return an array with boolean values:

In [32]:
a = np.arange(9).reshape(3, 3)
bool_arr = a < 4
print(bool_arr)

[[ True  True  True]
 [ True False False]
 [False False False]]


Now, what if we want to return each row where any of the elements is true, we can do that with `any` in combination with `where`:

In [33]:
# Return the indices of the rows where any column (axis=1) is true
indices = np.where(bool_arr.any(axis=1))
bool_arr[indices]
# You can see that the last row is excluded as this row doesn't contain any True values

array([[ True,  True,  True],
       [ True, False, False]])

And what if we want all elements in the row to be true? We can use `all`:

In [34]:
# If all values are true, return true (else false)
indices = np.where(bool_arr.all(axis=1))
bool_arr[indices]
# You can see that only the first row is included as this row is the only one to contain only True values

array([[ True,  True,  True]])

#### Numpy Unique and `in` checking

In [35]:
# Sometimes you just want to know all the unique values in a numpy array
# Luckily that function was already implemented for you
letters = ['A', 'B', 'C', 'D', 'D', 'A', 'E', 'F', 'G', 'H', 'Z']
np.unique(letters)

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'Z'], dtype='<U1')

In [37]:
# We can also easily check whether a big array exists,
# if it exists within a 1D vector.
np.isin(['X', 'C', 'M', 'Z'], letters)

array([False,  True, False,  True])

## Step 2: Practical Application of NumPy in Machine Learning

In this section, we will apply NumPy to a dataset from Scikit-learn. This will demonstrate how NumPy is used in real-world Machine Learning tasks, particularly for data representation and manipulation. 

In [38]:
import pandas as pd
titanic_data_df= pd.read_csv('data/titanic.csv')
titanic_data = titanic_data_df.to_numpy()


We can now look at the features present.

In [39]:
features = titanic_data_df.dtypes
features

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

**Question** How many features are present? (Find the length of the list above)

In [40]:
# START ANSWER
num_features=len(features)
# END ANSWER
print(num_features)

12


Usually, before applying any Machine Learning algorithm we always need to inspect the data to get a better idea of its structure and the necessary preprocessing steps that need to be performed.

**Question** Print the first 10 rows of the data to understand the structure.

In [42]:
# View the first few rows to understand the structure
# START ANSWER
print(titanic_data[:10])
# END ANSWER

[[1 0 3 'Mr. Owen Harris' 'male' 22.0 1 0 'A/5 21171' 7.25 nan 'S']
 [2 1 1 'Mrs. John Bradley (Florence Briggs Thayer)' 'female' 38.0 1 0
  'PC 17599' 71.2833 'C85' 'C']
 [3 1 3 'Miss. Laina' 'female' 26.0 0 0 'STON/O2. 3101282' 7.925 nan 'S']
 [4 1 1 'Mrs. Jacques Heath (Lily May Peel)' 'female' 35.0 1 0 '113803'
  53.1 'C123' 'S']
 [5 0 3 'Mr. William Henry' 'male' 35.0 0 0 '373450' 8.05 nan 'S']
 [6 0 3 'Mr. James' 'male' nan 0 0 '330877' 8.4583 nan 'Q']
 [7 0 1 'Mr. Timothy J' 'male' 54.0 0 0 '17463' 51.8625 'E46' 'S']
 [8 0 3 'Master. Gosta Leonard' 'male' 2.0 3 1 '349909' 21.075 nan 'S']
 [9 1 3 'Mrs. Oscar W (Elisabeth Vilhelmina Berg)' 'female' 27.0 0 2
  '347742' 11.1333 nan 'S']
 [10 1 2 'Mrs. Nicholas (Adele Achem)' 'female' 14.0 1 0 '237736' 30.0708
  nan 'C']]


**Question** What is the shape of `titanic_data`? What does each dimension correspond to?

In [44]:
# Print the current shape of titanic_data
titanic_shape = np.shape(titanic_data)
# START ANSWER
# END ANSWER
print(titanic_shape)


(891, 12)


**Question** Now, say that from the titanic data we only need the info from the first 15 passengers that tell their id, if they survived and the class in which they were traveling (three first columns). Select the desired subset from the `titanic_array` and put it into the variable `surviving_data`.

In [45]:
surviving_data = titanic_data[:15, :3]
print(titanic_data.shape)
# START ANSWER
# END ANSWER

print(surviving_data)
print('Selection correct: ', surviving_data.shape == (15,3))


(891, 12)
[[1 0 3]
 [2 1 1]
 [3 1 3]
 [4 1 1]
 [5 0 3]
 [6 0 3]
 [7 0 1]
 [8 0 3]
 [9 1 3]
 [10 1 2]
 [11 1 3]
 [12 1 1]
 [13 0 3]
 [14 0 3]
 [15 0 3]]
Selection correct:  True


**Question** The 2nd column (index 1) contains the information about the survival status of the passengers. It contains only 0s and 1s. What do these values stand for?

**Question** From the entire data, can you extract the information of all the passengers that survived? Hint: Use `np.where` to get the indices of the surviving passengers.

In [56]:
survived_idx = np.where(titanic_data[:, 1] == 1)[0]
titanic_survived = titanic_data[survived_idx]

# START ANSWER
# END ANSWER

print(titanic_survived)

[[2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 [4 1 1 ... 53.1 'C123' 'S']
 ...
 [881 1 2 ... 26.0 nan 'S']
 [888 1 1 ... 30.0 'B42' 'S']
 [890 1 1 ... 30.0 'C148' 'C']]


**Question** Can you give examples of some machine learning tasks that can be done with this data?

## Step 3: Practice Numpy


These are optional exercises, but highly recommended to get you familiar with some basic NumPy operations and tricks. If you get stuck, try to dive into the Numpy documentation first, to see if it can be of help as not all functions you need for the exercises are explained above.

### Array Calculations and Array Indexing
In all exercises below you are not allowed to use a loop.

In [58]:
# Given two arrays A and B each of the same size calculate their sum (elementwise) and their product (elementwise).
A = np.arange(5)
print(A)
B = np.arange(5, 10)
print(B)

def sum_arrays(A, B):
    result = None
    # START ANSWER
    result = A + B
    # END ANSWER
    return result

def multiply_arrays(A, B):
    result = None
    # START ANSWER
    result = A * B
    # END ANSWER
    return result

sum_AB = sum_arrays(A, B)
assert (sum_AB == np.array([ 5,  7,  9, 11, 13])).all()
mult_AB = multiply_arrays(A, B)
assert (mult_AB == np.array([ 0,  6, 14, 24, 36])).all()

sum_AB, mult_AB

[0 1 2 3 4]
[5 6 7 8 9]


(array([ 5,  7,  9, 11, 13]), array([ 0,  6, 14, 24, 36]))

In [63]:
# Given an array A with shape (128,) calculate the mean of the elements at even indexes.
A = np.arange(128)

def mean_even_idx(A):
    result = None
    # START ANSWER
    result = np.sum(A[::2]) / (np.shape(A)[0] / 2)
    # END ANSWER
    return result

mean_A = mean_even_idx(A)
print(mean_A)
assert mean_A == 63.0

mean_A

63.0


np.float64(63.0)

In [67]:
# Given an array A with shape (N,) make an array with all elements of A in reverse order
# and return as a matrix of size (N, 1).
A = np.arange(6)

def reverse(A):
    result = None
    # START ANSWER
    length = np.shape(A)[0]
    result = A[::-1].reshape(-1,1)
    # END ANSWER
    return result

rev = reverse(A)
assert (rev == np.array([[5],[4],[3],[2],[1],[0]])).all()
rev

array([[5],
       [4],
       [3],
       [2],
       [1],
       [0]])

#### Two dimensional data arrays
In this course you will be working a lot with matrices and vectors. The following exercises will let you practice with those.

Given is data matrix X with shape (m, n)

In [68]:
m = n = 5
X = np.arange(m * n).reshape(m, n)

print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [71]:
# Select the j-th column from the matrix X. What happens if you use X[j]? Is this correct?
j = 3
column = None
# START ANSWER
column = X.T[j]
# END ANSWER

assert (column == np.array([ 3,  8, 13, 18, 23])).all()
column

array([ 3,  8, 13, 18, 23])

In [72]:
# Given an ndarray X with shape (m,n), calculate the mean of each column.
# Try doing this without using np.mean or loops.
# Hint: try to sum up the entries and dividing them by the number of elements

means = 0
# START ANSWER
means = X.sum(axis=0) / X.shape[0]
# END ANSWER

assert (means == np.array([10., 11., 12., 13., 14.])).all()
means

array([10., 11., 12., 13., 14.])

In [73]:
# Now subtract the mean vector you just calculated from all the rows in your matrix leading to the 
# data matrix X_0. Yes this can be done without a loop! Hint: look at array broadcasting.

X_0 = None
# START ANSWER
X_0 = X - means
# END ANSWER

assert (X_0 == np.array([[-10., -10., -10., -10., -10.],
                         [ -5.,  -5.,  -5.,  -5.,  -5.],
                         [  0.,   0.,   0.,   0.,   0.],
                         [  5.,   5.,   5.,   5.,   5.],
                         [ 10.,  10.,  10.,  10.,  10.]])
       ).all()
X_0

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [75]:
# Given column j, find the largest element and return the entire row of this element.
# Hint: look at the function np.argmax for this.
X = np.random.rand(m, n)
j = 3

# START ANSWER
row_idx = np.argmax(X[:, j])
max_row = X[row_idx,:]
# END ANSWER

# Please inspect visually whether your code returns the right row
X, max_row

(array([[0.21271842, 0.2670563 , 0.09959553, 0.38367819, 0.31370714],
        [0.20894079, 0.45374821, 0.4735696 , 0.91685697, 0.43954413],
        [0.50689577, 0.68729177, 0.11672201, 0.33657621, 0.11581241],
        [0.37068425, 0.65259462, 0.10957544, 0.78627954, 0.23852679],
        [0.65275627, 0.60716974, 0.27272829, 0.81980578, 0.73053968]]),
 array([0.20894079, 0.45374821, 0.4735696 , 0.91685697, 0.43954413]))

#### Advanced Linear Algebra

In Python 3, the @ operator is introduced for matrix multiplication. Let A be an array of shape (m, n) and 
let B be an array of shape (n, k) then we can write A @ B for the matrix multiplication of A and B. 

Note that there is conceptual difference between a 1 dimensional array V of size (N,) 
and a vector V as we know it from linear algebra. In linear algebra, a vector with $N$ elements has dimensions $N \times 1$. 
A ‘vector’ V as a numpy array has shape (N,).




In [77]:
# Calculate the inner product of two vector v and w both of shape (N,).
# Validate your result by computing the dot product using multiply and sum operations.
v = np.arange(5)
w = np.arange(5, 10)

# START ANSWER
print(v)
print(w)
print(v.T @ w)
# END ANSWER

[0 1 2 3 4]
[5 6 7 8 9]
80


In [78]:
# Calculate the product of a matrix A of shape (M,N) with a vector v of shape (N,).
m = n = 5
X = np.arange(m * n).reshape(m, n)
v = np.arange(n)

product = None
# START ANSWER
product = X @ v
# END ANSWER

assert (product == np.array([ 30,  80, 130, 180, 230])).all()
product        

array([ 30,  80, 130, 180, 230])